"""create policies table

Revision ID: 049a28bfd81e
Revises: 0d755312994a
Create Date: 2026-02-02 14:21:56.219563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049a28bfd81e'
down_revision: Union[str, None] = '0d755312994a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database to this revision.
    
    Similar to Django's Migration.operations forward methods.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('feature', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('requests_per_day', sa.Integer(), nullable=True),
    sa.Column('requests_per_month', sa.Integer(), nullable=True),
    sa.Column('tokens_per_day', sa.Integer(), nullable=True),
    sa.Column('tokens_per_month', sa.Integer(), nullable=True),
    sa.Column('budget_per_day_usd', sa.Float(), nullable=True),
    sa.Column('budget_per_month_usd', sa.Float(), nullable=True),
    sa.Column('max_cost_per_request_usd', sa.Float(), nullable=True),
    sa.Column('allowed_models', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database from this revision.
    
    Similar to Django's Migration.operations reverse methods.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    # ### end Alembic commands ###
