"""add user plan and audit logs

Revision ID: 1f6811da7d4b
Revises: e25d9f8078da
Create Date: 2026-02-09 13:39:45.343611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6811da7d4b'
down_revision: Union[str, None] = 'e25d9f8078da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database to this revision.
    
    Similar to Django's Migration.operations forward methods.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database from this revision.
    
    Similar to Django's Migration.operations reverse methods.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
