"""add user plan and audit logs

Revision ID: e25d9f8078da
Revises: a4d1f85f0a8a
Create Date: 2026-02-09 13:37:06.559600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25d9f8078da'
down_revision: Union[str, None] = 'a4d1f85f0a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database to this revision.
    
    Similar to Django's Migration.operations forward methods.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database from this revision.
    
    Similar to Django's Migration.operations reverse methods.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
