"""add plan to users

Revision ID: e9e632f10bf2
Revises: f80f76adecf5
Create Date: 2026-02-09 11:24:35.568619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e632f10bf2'
down_revision: Union[str, None] = 'f80f76adecf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database to this revision.
    
    Similar to Django's Migration.operations forward methods.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database from this revision.
    
    Similar to Django's Migration.operations reverse methods.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
